# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alvo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'ALVO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AlvoEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_consumado', models.IntegerField()),
                ('Alvo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polsys.Alvo')),
            ],
            options={
                'db_table': 'ALVO_EVENTO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Armamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('is_artesanal', models.IntegerField(blank=True, null=True)),
                ('calibre', models.CharField(blank=True, max_length=10, null=True)),
                ('numeracao', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'ARMAMENTO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ArmamentoEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Armamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polsys.Armamento')),
            ],
            options={
                'db_table': 'ARMAMENTO_EVENTO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'BAIRRO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CidadeMg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('num_habitantes', models.IntegerField(blank=True, null=True)),
                ('latidude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('dpc_destinataria', models.CharField(blank=True, max_length=100, null=True)),
                ('regional_pcmg', models.CharField(blank=True, max_length=10, null=True)),
                ('departamento_pcmg', models.CharField(blank=True, max_length=10, null=True)),
                ('uf_fronteira', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'CIDADE_MG',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Comparsas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'COMPARSAS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('horario', models.TimeField(blank=True, null=True)),
                ('reds', models.CharField(blank=True, max_length=19, null=True)),
                ('is_disparo_via_publica', models.IntegerField()),
                ('is_disparo_bpm', models.IntegerField(blank=True, null=True)),
                ('is_disparo_dpc', models.IntegerField(blank=True, null=True)),
                ('is_troca_de_tiros', models.IntegerField(blank=True, null=True)),
                ('is_encapuzados', models.IntegerField(blank=True, null=True)),
                ('is_colete_balistico', models.CharField(blank=True, max_length=10, null=True)),
                ('is_miguelitos_fuga', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'EVENTO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FabricanteArmamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'FABRICANTE_ARMAMENTO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Faccao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'FACCAO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=10, null=True)),
                ('is_venda_controlada', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'MATERIAL',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MaterialEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polsys.Evento')),
                ('Material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polsys.Material')),
            ],
            options={
                'db_table': 'MATERIAL_EVENTO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ModusOperandi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'MODUS_OPERANDI',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ObjetoAlvo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'OBJETO_ALVO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SupeitoCrimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'SUPEITO_CRIMES',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Suspeito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('alcunha', models.CharField(blank=True, max_length=200, null=True)),
                ('rg', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('cpf', models.IntegerField(blank=True, null=True)),
                ('naturalidade', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('nome_da_mae', models.CharField(blank=True, max_length=100, null=True)),
                ('infopen', models.IntegerField(blank=True, null=True)),
                ('regiao', models.CharField(blank=True, max_length=100, null=True)),
                ('is_foto', models.IntegerField(blank=True, null=True)),
                ('fonte', models.CharField(blank=True, max_length=50, null=True)),
                ('data_ultima_prisao', models.DateField(blank=True, null=True)),
                ('is_monitoramento_sige', models.IntegerField(blank=True, null=True)),
                ('is_alta_periculosidade', models.IntegerField(blank=True, null=True)),
                ('is_confronto_policia', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SUSPEITO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SuspeitoAlvo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inclusao', models.DateField(blank=True, null=True)),
                ('Evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polsys.Evento')),
                ('Suspeito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polsys.Suspeito')),
            ],
            options={
                'db_table': 'SUSPEITO_ALVO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SuspeitoCidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CidadeMg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polsys.CidadeMg')),
                ('Suspeito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polsys.Suspeito')),
            ],
            options={
                'db_table': 'SUSPEITO_CIDADE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SuspeitoEventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polsys.Evento')),
                ('Suspeito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polsys.Suspeito')),
            ],
            options={
                'db_table': 'SUSPEITO_EVENTOS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoAlvo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'TIPO_ALVO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoArmamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'TIPO_ARMAMENTO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoEnvolvimentoSuspeito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'TIPO_ENVOLVIMENTO_SUSPEITO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoPenalCp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('art', models.IntegerField(blank=True, null=True)),
                ('paragrafo', models.CharField(blank=True, max_length=10, null=True)),
                ('inciso', models.CharField(blank=True, max_length=10, null=True)),
                ('alinea', models.CharField(blank=True, max_length=10, null=True)),
                ('item', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'TIPO_PENAL_CP',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoSituacaoPrisional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'TIPO_SITUACAO_PRISIONAL',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UnidadePrisional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'UNIDADE_PRISIONAL',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(blank=True, max_length=10, null=True)),
                ('nome', models.CharField(blank=True, max_length=10, null=True)),
                ('fabricante', models.CharField(blank=True, max_length=10, null=True)),
                ('is_caminhonete', models.CharField(blank=True, max_length=10, null=True)),
                ('is_importado', models.CharField(blank=True, max_length=10, null=True)),
                ('is_moto', models.CharField(blank=True, max_length=10, null=True)),
                ('is_clonado', models.CharField(blank=True, max_length=10, null=True)),
                ('is_roubado_furtado', models.CharField(blank=True, max_length=10, null=True)),
                ('is_alugado', models.CharField(blank=True, max_length=10, null=True)),
                ('cpf_proprietario', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'VEICULO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VeiculoEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polsys.Evento')),
                ('Veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polsys.Veiculo')),
            ],
            options={
                'db_table': 'VEICULO_EVENTO',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='suspeito',
            name='TipoEnvolvimentoSuspeito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polsys.TipoEnvolvimentoSuspeito'),
        ),
        migrations.AddField(
            model_name='suspeito',
            name='TipoSituacaoPrisional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polsys.TipoSituacaoPrisional'),
        ),
        migrations.AddField(
            model_name='suspeito',
            name='UnidadePrisional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polsys.UnidadePrisional'),
        ),
        migrations.AddField(
            model_name='suspeito',
            name='id_faccao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polsys.Faccao'),
        ),
        migrations.AddField(
            model_name='suspeito',
            name='id_modus_operandi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polsys.ModusOperandi'),
        ),
        migrations.AddField(
            model_name='supeitocrimes',
            name='Suspeito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polsys.Suspeito'),
        ),
        migrations.AddField(
            model_name='supeitocrimes',
            name='TipoPenalCp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polsys.TipoPenalCp'),
        ),
        migrations.AddField(
            model_name='evento',
            name='TipoPenalCp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polsys.TipoPenalCp'),
        ),
        migrations.AddField(
            model_name='evento',
            name='id_bairro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polsys.Bairro'),
        ),
        migrations.AddField(
            model_name='evento',
            name='id_cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polsys.CidadeMg'),
        ),
        migrations.AddField(
            model_name='comparsas',
            name='SuspeitoPrimario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SuspeitoPrimario', to='polsys.Suspeito'),
        ),
        migrations.AddField(
            model_name='comparsas',
            name='SuspeitoSecundario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SuspeitoSecundario', to='polsys.Suspeito'),
        ),
        migrations.AddField(
            model_name='bairro',
            name='CidadeMg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polsys.CidadeMg'),
        ),
        migrations.AddField(
            model_name='armamentoevento',
            name='Evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polsys.Evento'),
        ),
        migrations.AddField(
            model_name='armamento',
            name='FabricanteArmamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polsys.FabricanteArmamento'),
        ),
        migrations.AddField(
            model_name='armamento',
            name='TipoArmamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polsys.TipoArmamento'),
        ),
        migrations.AddField(
            model_name='alvoevento',
            name='Evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polsys.Evento'),
        ),
        migrations.AddField(
            model_name='alvoevento',
            name='ModusOperandi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polsys.ModusOperandi'),
        ),
        migrations.AddField(
            model_name='alvoevento',
            name='ObjetoAlvo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polsys.ObjetoAlvo'),
        ),
        migrations.AddField(
            model_name='alvo',
            name='TipoAlvo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polsys.TipoAlvo'),
        ),
        migrations.AlterUniqueTogether(
            name='veiculoevento',
            unique_together=set([('Veiculo', 'Evento')]),
        ),
        migrations.AlterUniqueTogether(
            name='suspeitoeventos',
            unique_together=set([('Evento', 'Suspeito')]),
        ),
        migrations.AlterUniqueTogether(
            name='suspeitocidade',
            unique_together=set([('CidadeMg', 'Suspeito')]),
        ),
        migrations.AlterUniqueTogether(
            name='suspeitoalvo',
            unique_together=set([('Evento', 'Suspeito')]),
        ),
        migrations.AlterUniqueTogether(
            name='supeitocrimes',
            unique_together=set([('TipoPenalCp', 'Suspeito')]),
        ),
        migrations.AlterUniqueTogether(
            name='materialevento',
            unique_together=set([('Material', 'Evento')]),
        ),
        migrations.AlterUniqueTogether(
            name='comparsas',
            unique_together=set([('SuspeitoPrimario', 'SuspeitoSecundario')]),
        ),
        migrations.AlterUniqueTogether(
            name='armamentoevento',
            unique_together=set([('Armamento', 'Evento')]),
        ),
        migrations.AlterUniqueTogether(
            name='alvoevento',
            unique_together=set([('Alvo', 'Evento')]),
        ),
    ]
