# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alvo',
            fields=[
                ('id_alvo', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'ALVO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Armamento',
            fields=[
                ('id_armamento', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('is_artesanal', models.IntegerField(blank=True, null=True)),
                ('calibre', models.CharField(blank=True, max_length=10, null=True)),
                ('numeracao', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'ARMAMENTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id_bairro', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'BAIRRO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CidadeMg',
            fields=[
                ('id_cidade', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('num_habitantes', models.IntegerField(blank=True, null=True)),
                ('latidude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('dpc_destinataria', models.CharField(blank=True, max_length=100, null=True)),
                ('regional_pcmg', models.CharField(blank=True, max_length=10, null=True)),
                ('departamento_pcmg', models.CharField(blank=True, max_length=10, null=True)),
                ('uf_fronteira', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'CIDADE_MG',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.DateField(blank=True, null=True)),
                ('horario', models.TimeField(blank=True, null=True)),
                ('reds', models.CharField(blank=True, max_length=19, null=True)),
                ('is_disparo_via_publica', models.IntegerField()),
                ('is_disparo_bpm', models.IntegerField(blank=True, null=True)),
                ('is_disparo_dpc', models.IntegerField(blank=True, null=True)),
                ('is_troca_de_tiros', models.IntegerField(blank=True, null=True)),
                ('is_encapuzados', models.IntegerField(blank=True, null=True)),
                ('is_colete_balistico', models.CharField(blank=True, max_length=10, null=True)),
                ('is_miguelitos_fuga', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'EVENTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FabricanteArmamento',
            fields=[
                ('id_fabricante_armamento', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'FABRICANTE_ARMAMENTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Faccao',
            fields=[
                ('id_faccao', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'FACCAO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id_material', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=10, null=True)),
                ('is_venda_controlada', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'MATERIAL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModusOperandi',
            fields=[
                ('id_modus_operandi', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'MODUS_OPERANDI',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObjetoAlvo',
            fields=[
                ('id_objeto_alvo', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'OBJETO_ALVO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suspeito',
            fields=[
                ('id_suspeito', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('alcunha', models.CharField(blank=True, max_length=200, null=True)),
                ('rg', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('cpf', models.IntegerField(blank=True, null=True)),
                ('naturalidade', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('nome_da_mae', models.CharField(blank=True, max_length=100, null=True)),
                ('infopen', models.IntegerField(blank=True, null=True)),
                ('regiao', models.CharField(blank=True, max_length=100, null=True)),
                ('is_foto', models.IntegerField(blank=True, null=True)),
                ('fonte', models.CharField(blank=True, max_length=50, null=True)),
                ('data_ultima_prisao', models.DateField(blank=True, null=True)),
                ('is_monitoramento_sige', models.IntegerField(blank=True, null=True)),
                ('is_alta_periculosidade', models.IntegerField(blank=True, null=True)),
                ('is_confronto_policia', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SUSPEITO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoAlvo',
            fields=[
                ('id_tipo_alvo', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'TIPO_ALVO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoArmamento',
            fields=[
                ('id_tipo_armamento', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'TIPO_ARMAMENTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEnvolvimentoSuspeito',
            fields=[
                ('id_tipo_envolvimento_suspeito', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'TIPO_ENVOLVIMENTO_SUSPEITO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPenalCp',
            fields=[
                ('id_tipo_penal', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('art', models.IntegerField(blank=True, null=True)),
                ('paragrafo', models.CharField(blank=True, max_length=10, null=True)),
                ('inciso', models.CharField(blank=True, max_length=10, null=True)),
                ('alinea', models.CharField(blank=True, max_length=10, null=True)),
                ('item', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'TIPO_PENAL_CP',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoSituacaoPrisional',
            fields=[
                ('id_tipo_situacao_prisional', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'TIPO_SITUACAO_PRISIONAL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadePrisional',
            fields=[
                ('id_unidade_prisional', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'UNIDADE_PRISIONAL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id_veiculo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('placa', models.CharField(blank=True, max_length=10, null=True)),
                ('nome', models.CharField(blank=True, max_length=10, null=True)),
                ('fabricante', models.CharField(blank=True, max_length=10, null=True)),
                ('is_caminhonete', models.CharField(blank=True, max_length=10, null=True)),
                ('is_importado', models.CharField(blank=True, max_length=10, null=True)),
                ('is_moto', models.CharField(blank=True, max_length=10, null=True)),
                ('is_clonado', models.CharField(blank=True, max_length=10, null=True)),
                ('is_roubado_furtado', models.CharField(blank=True, max_length=10, null=True)),
                ('is_alugado', models.CharField(blank=True, max_length=10, null=True)),
                ('cpf_proprietario', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'VEICULO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlvoEvento',
            fields=[
                ('id_alvo', models.ForeignKey(db_column='id_alvo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='polsys.Alvo')),
                ('is_consumado', models.IntegerField()),
            ],
            options={
                'db_table': 'ALVO_EVENTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArmamentoEvento',
            fields=[
                ('id_armamento', models.ForeignKey(db_column='id_armamento', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='polsys.Armamento')),
            ],
            options={
                'db_table': 'ARMAMENTO_EVENTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comparsas',
            fields=[
                ('id_suspeito_primario', models.ForeignKey(db_column='id_suspeito_primario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='suspeitoprimario', serialize=False, to='polsys.Suspeito')),
            ],
            options={
                'db_table': 'COMPARSAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialEvento',
            fields=[
                ('id_material', models.ForeignKey(db_column='id_material', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='polsys.Material')),
            ],
            options={
                'db_table': 'MATERIAL_EVENTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SupeitoCrimes',
            fields=[
                ('id_tipo_penal', models.ForeignKey(db_column='id_tipo_penal', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='polsys.TipoPenalCp')),
            ],
            options={
                'db_table': 'SUPEITO_CRIMES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SuspeitoAlvo',
            fields=[
                ('id_evento', models.ForeignKey(db_column='id_evento', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='polsys.Evento')),
                ('data_inclusao', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SUSPEITO_ALVO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SuspeitoCidade',
            fields=[
                ('id_cidade', models.ForeignKey(db_column='id_cidade', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='polsys.CidadeMg')),
            ],
            options={
                'db_table': 'SUSPEITO_CIDADE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SuspeitoEventos',
            fields=[
                ('id_evento', models.ForeignKey(db_column='id_evento', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='polsys.Evento')),
            ],
            options={
                'db_table': 'SUSPEITO_EVENTOS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VeiculoEvento',
            fields=[
                ('id_veiculo', models.ForeignKey(db_column='id_veiculo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='polsys.Veiculo')),
            ],
            options={
                'db_table': 'VEICULO_EVENTO',
                'managed': False,
            },
        ),
    ]
