# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polsys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alvo',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='alvoevento',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='armamento',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='armamentoevento',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='bairro',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='cidademg',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='comparsas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='fabricantearmamento',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='faccao',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='materialevento',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='modusoperandi',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='objetoalvo',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='supeitocrimes',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='suspeito',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='suspeitoalvo',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='suspeitocidade',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='suspeitoeventos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tipoalvo',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tipoarmamento',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tipoenvolvimentosuspeito',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tipopenalcp',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tiposituacaoprisional',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='unidadeprisional',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='veiculo',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='veiculoevento',
            options={'managed': True},
        ),
    ]
